import { Inter } from 'next/font/google'
import './globals.css'
import { Box, ChakraProvider } from "@chakra-ui/react"
import Footer from '@/components/footer/footer'
import { ArenaProvider } from '@/context/arenaProvider'
import NavBar from '@/components/navbar/navbar'
import { Body } from '@/components/body/body'
import Content from '@/components/content'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ChakraProvider>
        <ArenaProvider>
        <Box >
          <NavBar/>
        </Box>
        <Box>
          <Content content={<Body/>} />
        </Box>

          <Box>
            <Footer />
          </Box>
          <body className={inter.className}>{children}</body>
        </ArenaProvider>
      </ChakraProvider>
</html>
  )
}
