import { Inter } from 'next/font/google'
import './globals.css'
import { Box, ChakraProvider, Flex } from "@chakra-ui/react"
import Footer from '@/components/footer/footer'
import { ArenaProvider } from '@/context/arenaProvider'
import NavBar from '@/components/navbar/navbar'



export const metadata = {
  title: 'Arena Negra Restaurante',
  description: 'Generated by Javier Visconti',
}

export default function RootLayout({ children }) {
  return (
    <ChakraProvider>
      <ArenaProvider>
        <Flex direction="column" minH="100vh">
          <NavBar/>
          <Box flex="1">
            {children}
          </Box>
          <Footer />
        </Flex>
      </ArenaProvider>
    </ChakraProvider>
  )
}
