import { Inter } from 'next/font/google'
import './globals.css'
import { ChakraProvider } from "@chakra-ui/react"
import Footer from '@/components/footer/footer'
import { ArenaProvider } from '@/context/arenaProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ChakraProvider>
        <ArenaProvider>
          <body className={inter.className}>{children}</body>
          <Footer />
        </ArenaProvider>
      </ChakraProvider>
</html>
  )
}
